---
name: EHM 
options:
  deploymentTarget:
    iOS: 15.0
  defaultConfig: Debug
  developmentLanguage: "ru"
  enableBaseInternationalization: true
  indentWidth: 4

configs:
  Debug: debug
  Release: release

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    version: 5.6.0
  PDFGenerator:
    url: https://github.com/rursache/PDFGenerator
    version: 4.0.0

settings:
  base:
    SWIFT_VERSION: 5.5
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
    TARGETED_DEVICE_FAMILY: 1
    SUPPORTS_MACCATALYST: NO
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: ["$(inherited)", "DEBUG"]
      SWIFT_COMPILATION_MODE: incremental
    Release:
      SWIFT_COMPILATION_MODE: wholemodule

targets:
  EHM:
    type: application
    platform: iOS
    dependencies:
      - package: SnapKit
      - package: PDFGenerator
    sources:
      - path: ./EHM
    configFiles:
      Release: Config/EHM.xcconfig
      Debug: Config/EHM.xcconfig
    settings:
      base:
        MARKETING_VERSION: $(EHM_MARKETING_VERSION)
        CURRENT_PROJECT_VERSION: $(EHM_MARKETING_SUB_VERSION)
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: bekrenev.aleksandr.EHM
        DEVELOPMENT_TEAM: 8F9BJF9KQ5
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    postCompileScripts:
      - script: |
          if [[ -f ./Binaries/swiftlint/swiftlint ]]; then
            make lint
          else 
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: SwiftLint

schemes:
  EHM:
    build:
      targets:
        EHM: all
    run:
      config: Debug
      environmentVariables:
        OS_ACTIVITY_MODE: disable
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  EHM Release:
    build:
      targets:
        EHM: all
    run:
      config: Release
      environmentVariables:
        OS_ACTIVITY_MODE: disable
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release
